int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int squareroot(int x, int i);
int is_prime_number(int n);
int isprime(int x, int i);
int is_palindrome(char *s);
int ispal(char *s, int i, int len);
int wildcmp(char *s1, char *s2);
